// <auto-generated />
using System;
using Documents.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Documents.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DocumentsDbContext))]
    partial class DocumentsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Documents.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid?>("CandidatureId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CandidatureId");

                    b.Property<string>("CheminFichier")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("CheminFichier");

                    b.Property<string>("CommentaireVerificateur")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("CommentaireVerificateur");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ContentType");

                    b.Property<DateTime>("DateDepot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DateDepot")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DateMiseAJour")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateMiseAJour");

                    b.Property<DateTime?>("DateValidation")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateValidation");

                    b.Property<Guid?>("DocumentPrecedentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DocumentPrecedentId");

                    b.Property<bool>("EstVersionCourante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("EstVersionCourante");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Extension");

                    b.Property<string>("NomFichier")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("NomFichier");

                    b.Property<string>("NomFichierStockage")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("NomFichierStockage");

                    b.Property<int>("StagiaireId")
                        .HasColumnType("int")
                        .HasColumnName("StagiaireId");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValue("EnAttente")
                        .HasColumnName("Statut");

                    b.Property<long>("TailleFichierOctets")
                        .HasColumnType("bigint")
                        .HasColumnName("TailleFichierOctets");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Type");

                    b.Property<int?>("VerificateurId")
                        .HasColumnType("int")
                        .HasColumnName("VerificateurId");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("Version");

                    b.HasKey("Id");

                    b.HasIndex("CandidatureId")
                        .HasDatabaseName("IX_Document_CandidatureId");

                    b.HasIndex("EstVersionCourante")
                        .HasDatabaseName("IX_Document_EstVersionCourante");

                    b.HasIndex("StagiaireId")
                        .HasDatabaseName("IX_Document_StagiaireId");

                    b.HasIndex("Statut")
                        .HasDatabaseName("IX_Document_Statut");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_Document_Type");

                    b.HasIndex("StagiaireId", "Type", "EstVersionCourante")
                        .HasDatabaseName("IX_Document_StagiaireId_Type_Version");

                    b.ToTable("Documents", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
