// <auto-generated />
using System;
using Candidatures.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Candidatures.Infrastructure.Migrations
{
    [DbContext(typeof(CandidaturesDbContext))]
    [Migration("20260720092404_AddDestinataireTransmission")]
    partial class AddDestinataireTransmission
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Candidatures.Domain.Entities.Candidature", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Commentaire")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("Commentaire");

                    b.Property<string>("CvFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CvFileName");

                    b.Property<string>("CvPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("CvPath");

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DateCreation")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDecision")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateDecision");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateMiseAJour")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateMiseAJour");

                    b.Property<DateTime?>("DateTransmissionDirection")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateTransmissionDirection");

                    b.Property<int>("DepartementId")
                        .HasColumnType("int")
                        .HasColumnName("DepartementId");

                    b.Property<string>("DestinataireTransmission")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DureeStageMois")
                        .HasColumnType("int");

                    b.Property<string>("Ecole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EncadrantId")
                        .HasColumnType("int")
                        .HasColumnName("EncadrantId");

                    b.Property<string>("LettreMotivation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NiveauEtude")
                        .HasColumnType("int");

                    b.Property<int>("SpecialiteId")
                        .HasColumnType("int")
                        .HasColumnName("SpecialiteId");

                    b.Property<int>("StagiaireId")
                        .HasColumnType("int")
                        .HasColumnName("StagiaireId");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValue("EnAttente")
                        .HasColumnName("Statut");

                    b.Property<bool>("TransmisADirection")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("TransmisADirection");

                    b.HasKey("Id");

                    b.HasIndex("EncadrantId")
                        .HasDatabaseName("IX_Candidature_EncadrantId");

                    b.HasIndex("StagiaireId")
                        .HasDatabaseName("IX_Candidature_StagiaireId");

                    b.HasIndex("Statut")
                        .HasDatabaseName("IX_Candidature_Statut");

                    b.HasIndex("StagiaireId", "Statut")
                        .HasDatabaseName("IX_Candidature_StagiaireId_Statut");

                    b.ToTable("Candidatures", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
